dist: xenial
language: python
python:
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran
install:
  - python setup.py install
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - pip install coverage
  - coverage run setup.py test
